# Generated by Django 6.0.2 on 2026-02-20 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('email_messages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Дата и время начала отправки')),
                ('end_time', models.DateTimeField(verbose_name='Дата и время окончания отправки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                (
                    'clients',
                    models.ManyToManyField(related_name='mailings', to='clients.client', verbose_name='Клиенты'),
                ),
                (
                    'message',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='mailings',
                        to='email_messages.emailmessage',
                        verbose_name='Сообщение',
                    ),
                ),
                (
                    'owner',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='mailings',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Владелец',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MailingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'status',
                    models.CharField(
                        choices=[('success', 'Успешно'), ('failed', 'Не успешно')],
                        max_length=20,
                        verbose_name='Статус',
                    ),
                ),
                ('server_response', models.TextField(blank=True, verbose_name='Ответ сервера')),
                ('attempted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время попытки')),
                (
                    'client',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='attempts',
                        to='clients.client',
                        verbose_name='Клиент',
                    ),
                ),
                (
                    'mailing',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='attempts',
                        to='mailings.mailing',
                        verbose_name='Рассылка',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Попытка рассылки',
                'verbose_name_plural': 'Попытки рассылок',
                'ordering': ['-attempted_at'],
            },
        ),
    ]
