# Generated by Django 6.0.2 on 2026-02-21 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={
                'ordering': ['-created_at'],
                'permissions': [('can_disable_mailing', 'Может отключать рассылки')],
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.AddField(
            model_name='mailing',
            name='status',
            field=models.CharField(
                choices=[
                    ('created', 'Создана'),
                    ('started', 'Запущена'),
                    ('completed', 'Завершена'),
                    ('disabled', 'Отключена'),
                ],
                default='created',
                max_length=20,
                verbose_name='Статус',
            ),
        ),
    ]
