# Generated by Django 6.0.2 on 2026-02-21 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0002_alter_mailing_options_mailing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='name',
            field=models.CharField(
                default='Новая рассылка',
                help_text='Введите название для идентификации рассылки',
                max_length=255,
                verbose_name='Название рассылки',
            ),
            preserve_default=False,
        ),
    ]
