# Generated by Django 6.0.2 on 2026-02-21 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0003_mailing_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='frequency',
            field=models.CharField(
                choices=[('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('monthly', 'Ежемесячно')],
                default='daily',
                help_text='Как часто отправлять рассылку',
                max_length=20,
                verbose_name='Периодичность',
            ),
        ),
    ]
